eureka:
  instance:
    lease-renewal-interval-in-seconds: 5      # 心跳时间，即服务续约间隔时间（缺省为30s）
    lease-expiration-duration-in-seconds: 10  # 发呆时间，即服务续约到期时间（缺省为90s）
  client:
    healthcheck:
      enabled: true                           # 开启健康检查（依赖spring-boot-starter-actuator）
    service-url:
      defaultZone: http://localhost:2000/eureka/
#  instance:
#    appname: zuul

#  port: 1121
zuul:
  routes:
    base:
      path: /base/**
      serviceId: ks-base  # 转发到消费者 /ribbon/
#    feign:
#      path: /feign/**
#      serviceId: ks-base  # 转发到消费者 /feign/

ribbon:
  eureka:
    enabled: false
spring:
  application:
    name: ks-zuul
logging:
  file: /data/lottery_pay/runge-base/zuul/log/zuul.log