spring:
  profiles:
    active: dev
server:
  port: 2002
tencent:
  msg:
    appid: 1400237690
    appkey: "8757056432f4b2a4870a938468a07521"
    smsSign: "看啥网"
    templateId: 387563
    time: 30
mail:
  myEmail: kansha@kansha.net.cn
  myEmailPassword: pzy78216795
  myEmailSMTPHost: smtp.ym.163.com #网易企业免费邮箱
  mySmtpPort: 25